export const enum AuthProviderTypeModel {
  DEFAULT = 'DEFAULT',

  MOCKED_USER_DATA = 'MOCKED_USER_DATA',

  OAUTH2_KEYCLOAK = 'OAUTH2_KEYCLOAK',

  OAUTH2_SOCIAL_FACEBOOK = 'OAUTH2_SOCIAL_FACEBOOK',

  OAUTH2_SOCIAL_GOOGLE = 'OAUTH2_SOCIAL_GOOGLE',

  SUITECRM7 = 'SUITECRM7',

  LARAVEL9 = 'LARAVEL9',

}
